node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/yousselg/sample-spring-microservices.git', credentialsId: 'github-yousselg', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('game-service') {
                def app = docker.build "localhost:5000/game-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/game-service:${env.version}").run('-p 3333:3333 -h game --name game --link discovery --link player')
        }

        stage ('Final') {
            build job: 'gateway-service-pipeline', wait: false
        }      

    }

}