info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account:
      path: /players/**
      serviceId: player-service
    customer:
      path: /games/**
      serviceId: game-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG