 using hostname.

[code language="java"]
node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/yousselg/sample-spring-microservices.git', credentialsId: 'github-yousselg', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('player-service') {
                def app = docker.build "localhost:5000/player-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("localhost:5000/player-service:${env.version}").run('-p 2222:2222 -h player --name player --link discovery')
        }

        stage ('Final') {
            build job: 'game-service-pipeline', wait: false
        }      

    }

}